### ISSUE TITLE
gulp4 doesn't work

### ISSUE THREAD

**Issue by weickdev** [BootstrapDash/Stellar#2]
when I run gulp serve, I get below error:
```
assert.js:43
  throw new errors.AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/weichengke/codes/Stellar/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/weichengke/codes/Stellar/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/weichengke/codes/Stellar/gulpfile.js:23:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

My gup version is:
```
CLI version: 2.2.0
Local version: 4.0.2
```

**Comment by bootstrapdash-team** [comment]
@weickdev This template was initially built on gulp 3. Now, we have updated it to gulp 4. Please download the latest version and try again.
